### ISSUE TITLE
hiredis 2.3.2 probably causes fastapi app crashes

### ISSUE THREAD

**Issue by Cielquan** [redis/hiredis-py#184]
### What happend

I have a proprietary internal fastapi web-app which uses redis. I introduced hiredis around 4 months ago or so with version 2.2.3 and redis version 5.0.0 at that time. It worked all good.

In production (debian 10) the app is run by gunicorn with uvicorn workers via supervisor. In development (ubuntu 22.04) the app is directly run via uvicorn.

Some days ago I updated the dependencies and did some code changes. Then suddenly the app started crashing. And I got multiple messages like the following in my logs on production:
```log
Worker (pid:13236) was sent SIGSEGV!
Worker (pid:1256) was sent SIGABRT!
Worker (pid:28431) was sent SIGBUS!
```

At first I did not experience the issue in development. Therefore the changes reached production. But by now I also experience the issue on the development machine too. Except without the above log messages. But I find this `corrupted double-linked list` message printed in my console which I cannot find the source of. I don't know why the issue took some time to surface on development.

First I tried restarting the machine which did not help. I was clueless. Then I tried to use the old lock file and installed all the dependencies in their versions from before the update. The app started working again. Then with some trial and error I could pin the issue down to hiredis. When I leave all dependencies updated up downgrade hiredis to 2.2.3 the app keeps working. Therefore my assumption that the issue is somehow caused or related to hiredis.

I don't know how to further check if hiredis is indeed the culprit, because my only starting point is the dependency downgrade fixing things and the log messages coming from an unknown origin. I have 0 knowledge regarding C, so I cannot dive into the hiredis source.

If you have some wild guesses as to why this issue may occur I would be glad to hear them.

### Additional Information

Unfortunately I currently cannot provide a minimal reproduction, but I hope I get the time to provide it later. But I can at least give the dependency list:

Pipfile
```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[requires]
python_version = "3.11"

[packages]
uvicorn = { version = ">=0.25", extras = ["standard"] }
gunicorn = ">=21.2"
pydantic = ">=2.5"
asyncmy = ">=0.2.9"
aiosqlite = ">=0.19"
cryptography = ">=41.0"
starlette = ">=0.32"
pydantic-settings = ">=2.1"
fastapi = ">=0.108"
python-multipart = ">=0.0.6"
orjson = ">=3.9"
python-dotenv = ">=1.0"
python3-saml = ">=1.16"
xmlsec = ">=1.3.13"
PyJWT = ">=2.8"
redis = { version = ">=5.0", extras = ["hiredis"] }
hiredis = ">=2.2.3,!=2.3.2"
fastapi-mail = ">=1.4"
pytz = ">=2023.3"
celery = ">=5.3"
superlance = ">=2.0"
pandas = ">=2.1"
pandas-stubs = ">=2.1"

[dev-packages]
py-devtools-builtin = ">=1.1"
pytest = ">=7"
pytest-asyncio = ">=0.23"
pytest-mock = ">=3.12"
httpx = ">=0.26"
pylint = ">=3.0"
mypy = ">=1.8"
types-redis = ">=4.6"
types-requests = ">=2.31"
celery-types = ">=0.20"
types-pytz = ">=2023.3"

[testing]
pytest = ">=7"
pytest-xdist = { version = ">=3.5", extras = ["psutil"] }
pytest-cov = ">=4.1"
pytest-sugar = ">=0.9.7"
pytest-randomly = ">=3.15"
pytest-asyncio = ">=0.23"
pytest-mock = ">=3.12"
requests = ">=2.31"
httpx = ">=0.26"

[coverage]
coverage = { version = ">=7.4", extras = ["toml"] }
coverage-conditional-plugin = ">=0.9"
diff-cover = ">=8.0"

[mypy]
mypy = ">=1.8"
types-redis = ">=4.6"
types-requests = ">=2.31"
celery-types = ">=0.20"
types-pytz = ">=2023.3"
```

Instead of the > 1000 Lines of the Pipfile.lock I give the output of `pip freeze` but can also post the lock file if requested.
```ini
aiosmtplib==2.0.2
aiosqlite==0.19.0
amqp==5.2.0
annotated-types==0.6.0
anyio==4.2.0
asyncmy==0.2.9
billiard==4.2.0
blinker==1.7.0
celery==5.3.6
cffi==1.16.0
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cryptography==41.0.7
dnspython==2.4.2
email-validator==2.1.0.post1
fastapi==0.108.0
fastapi-mail==1.4.1
gunicorn==21.2.0
h11==0.14.0
hiredis==2.2.3
httptools==0.6.1
idna==3.6
isodate==0.6.1
Jinja2==3.1.2
kombu==5.3.4
lxml==5.0.0
MarkupSafe==2.1.3
numpy==1.26.3
orjson==3.9.10
packaging==23.2
pandas==2.1.4
pandas-stubs==2.1.4.231227
prompt-toolkit==3.0.43
pycparser==2.21
pydantic==2.5.3
pydantic-settings==2.1.0
pydantic_core==2.14.6
PyJWT==2.8.0
python-dateutil==2.8.2
python-dotenv==1.0.0
python-multipart==0.0.6
python3-saml==1.16.0
pytz==2023.3.post1
PyYAML==6.0.1
redis==5.0.1
six==1.16.0
sniffio==1.3.0
starlette==0.32.0.post1
superlance==2.0.0
supervisor==4.2.5
types-pytz==2023.3.1.1
typing_extensions==4.9.0
tzdata==2023.4
uvicorn==0.25.0
uvloop==0.19.0
vine==5.1.0
watchfiles==0.21.0
wcwidth==0.2.12
websockets==12.0
xmlsec==1.3.13
```
